[build]
  command = "npm ci && npm run build"
  publish = "public"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[context.production.environment]
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV           = "production"
  HUGO_VERSION       = "0.164.0"
  NODE_VERSION       = "24"

[context.split1]
  command = "npm ci && npm run build -- --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.164.0"
    NODE_VERSION = "24"

[context.deploy-preview]
  command = "npm ci && npm run build:future -- -b $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
    HUGO_VERSION = "0.164.0"
    NODE_VERSION = "24"

[context.branch-deploy]
  command = "npm ci && npm run build -- -b $DEPLOY_PRIME_URL"

  [context.branch-deploy.environment]
    HUGO_VERSION = "0.164.0"
    NODE_VERSION = "24"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "document-domain=()"
    X-Permitted-Cross-Domain-Policies = "none"
